### PR TITLE
make hardnested compile on gcc 4.9.2

### LINKED ISSUE #300: older compiler error with new hardnested
gcc 4.9.2 on mingw errors here: (similar to :https://github.com/p12tic/libsimdpp/issues/28 )
```cmdhfmfhard.c: In function 'get_SIMD_instruction_set':
cmdhfmfhard.c:72:2: error: Parameter to builtin not valid: avx512f
  if (__builtin_cpu_supports("avx512f")) strcpy(instruction_set, "AVX512F");
  ^
make[1]: *** [obj/cmdhfmfhard.o] Error 1
make: *** [client/all] Error 2

### PR DESCRIPTION
**Pull request by marshmellow42**
plus add Td to gitignore.

unless someone has a better solution ;) this fixes #300 for me. (and probably @Gator96100 )

### CODE REVIEW

**Comment by pwpiwi** [comment]
Excellent!

**Comment by thesle3p** [comment]
this breaks compiles on kali/kali nethunter.

**Comment by pwpiwi** [comment]
Compiles fine on my Kali. Can you please be more specific? Errors? Warnings?

**Comment by pwpiwi** [comment]
Kali Nethunter on Nexus? hf mf hardnested will not work in this case because it makes use of Intel SIMD instructions. But we should make it compile nevertheless - either by disabling hf mf hardnested in this case or providing a non-SIMD (slooooooooow) alternative.

**Comment by thesle3p** [comment]
I get ```unrecognized command line option '-mno-mmx' 
unrecognized command line option '-mno-sse2'; did you mean '-fno-dse'?
unrecognized command line option '-mno-avx'; did you mean '-Who-a'?
unrecognized command line option 'mno-avx2'; did you mean '-Who-a'?
unrecognized command line option '-mno-avx512f'
```
