### PR TITLE
fix: AVX512 detection

### PR DESCRIPTION
**Pull request by pwpiwi**

### CODE REVIEW

**Comment by iceman1001** [comment]
Have you tested it on a gcc which doesn't support -mavx512f  ?

**Comment by pwpiwi** [comment]
No. But I have tested with `-mavx1024`.

**Comment by iceman1001** [comment]
bugger.  that fix didn't work on ubuntu 16.04



> 
> /home/user/proxmark3/client/hardnested/hardnested_bf_core.c:556: undefined reference to `crack_states_bitsliced_AVX512'
> /home/user/proxmark3/client/hardnested/hardnested_bf_core.c:556: undefined reference to `crack_states_bitsliced_AVX512'
> obj/hardnested/hardnested_bf_core_NOSIMD.o: In function `bitslice_test_nonces_dispatch':
> /home/user/proxmark3/client/hardnested/hardnested_bf_core.c:591: undefined reference to `bitslice_test_nonces_AVX512'
> /home/user/proxmark3/client/hardnested/hardnested_bf_core.c:577: undefined reference to `bitslice_test_nonces_AVX512'
> obj/hardnested/hardnested_bitarray_core_NOSIMD.o: In function `malloc_bitarray_dispatch':
> /home/user/proxmark3/client/hardnested/hardnested_bitarray_core.c:324: undefined reference to `malloc_bitarray_AVX512'
> /home/user/proxmark3/client/hardnested/hardnested_bitarray_core.c:324: undefined reference to `malloc_bitarray_AVX512'
> obj/hardnested/hardnested_bitarray_core_NOSIMD.o: In function `free_bitarray_dispatch':
> /home/user/proxmark3/client/hardnested/hardnested_bitarray_core.c:345: undefined reference to `free_bitarray_AVX512'
> /home/user/proxmark3/client/hardnested/hardnested_bitarray_core.c:345: undefined reference to `free_bitarray_AVX512'
> obj/hardnested/hardnested_bitarray_core_NOSIMD.o: In function `bitcount_dispatch':
>

**Comment by pwpiwi** [comment]
Huh? That would happen if the compiler supports the AVX512 instruction set but doesn't support the option `-mavx512f` ?

Did it compile with or without `-mavx512f` and `-mno-avx512f` ?

**Comment by iceman1001** [comment]
> gcc -MT obj/hardnested/hardnested_bf_core_NOSIMD.o -MMD -MP -MF obj/hardnested/hardnested_bf_core.Td  -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I../uart -I/opt/local/include -I../liblua -Wall -g -O3 -DHAVE_GUI -mno-mmx -mno-sse2 -mno-avx -mno-avx2 -c -o obj/hardnested/hardnested_bf_core_NOSIMD.o hardnested/hardnested_bf_core.c

**Comment by iceman1001** [comment]
when using this fix.

**Comment by pwpiwi** [comment]
What is the output of
```
echo | gcc -E -mavx512f -
```
and then the full command
```
echo | gcc -E -mavx512f - &> /dev/null && echo "True"
```

**Comment by iceman1001** [comment]
user@ubuntu:~/proxmark3/client$ echo | gcc -E -mavx512f -
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
user@ubuntu:~/proxmark3/client$

**Comment by iceman1001** [comment]
```
user@ubuntu:~/proxmark3/client$ echo | gcc -E -mavx512f - &> /dev/null && echo "True"
True
user@ubuntu:~/proxmark3/client$ 
```

**Comment by iceman1001** [comment]
```
user@ubuntu:~/proxmark3/client$ make print-SUPPORTS_AVX512
SUPPORTS_AVX512 = True
user@ubuntu:~/proxmark3/client$ 

```

**Comment by iceman1001** [comment]
its the subset definition  __AVX512F__  that doesn't work inside  hardnested_bf_core.c

**Comment by iceman1001** [comment]
i think the fix falsely claims 512 support.  When doing native..
```
user@ubuntu:~/proxmark3$ gcc -march=native -dM -E - < /dev/null | egrep "SSE|AVX" |sort
#define __AVX__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSSE3__ 1

```

**Comment by iceman1001** [comment]
hm.. doesn't make sense..

```
user@ubuntu:~/proxmark3$ echo | gcc -dM -E -mavx512f - < /dev/null | egrep "SSE|AVX" | sort
#define __AVX__ 1
#define __AVX2__ 1
#define __AVX512F__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSSE3__ 1
user@ubuntu:~/proxmark
```

**Comment by iceman1001** [comment]
looks like objectlinker gets confused.    It tries to link NO_SIMD.o with the AVX512f ....


```
$(OBJDIR)/%_NOSIMD.o : %.c $(OBJDIR)/%.d
	$(CC) $(DEPFLAGS) $(CFLAGS) $(HARD_SWITCH_NOSIMD) -c -o $@ $<

$(OBJDIR)/%_MMX.o : %.c $(OBJDIR)/%.d
	$(CC) $(DEPFLAGS) $(CFLAGS) $(HARD_SWITCH_MMX) -c -o $@ $<

$(OBJDIR)/%_SSE2.o : %.c $(OBJDIR)/%.d
	$(CC) $(DEPFLAGS) $(CFLAGS) $(HARD_SWITCH_SSE2) -c -o $@ $<

$(OBJDIR)/%_AVX.o : %.c $(OBJDIR)/%.d
	$(CC) $(DEPFLAGS) $(CFLAGS) $(HARD_SWITCH_AVX) -c -o $@ $<

$(OBJDIR)/%_AVX2.o : %.c $(OBJDIR)/%.d
	$(CC) $(DEPFLAGS) $(CFLAGS) $(HARD_SWITCH_AVX2) -c -o $@ $<

$(OBJDIR)/%_AVX512.o : %.c $(OBJDIR)/%.d
	$(CC) $(DEPFLAGS) $(CFLAGS) $(HARD_SWITCH_AVX512) -c -o $@ $<
```

**Comment by uzlonewolf** [comment]
Works great on Fedora :-/

What's the output of your ```gcc -version``` ?  I'm wondering if the version check was actually broken for you as well but gcc was compiled in such a way that not including -mavx512f is the correct thing to do...

**Comment by uzlonewolf** [comment]
On mine,
```
client]$ gcc -dM -E -march=native - < /dev/null | egrep "SSE|AVX" | sort
#define __AVX__ 1
#define __AVX2__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```
```
client]$ gcc -dM -E -mavx512f - < /dev/null | egrep "SSE|AVX" | sort
#define __AVX__ 1
#define __AVX2__ 1
#define __AVX512F__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```

**Comment by pwpiwi** [comment]
Please try #508. Now passes Travis tests.
